name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow the workflow to be triggered manually

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup cache for Bundler
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            Gemfile.lock
            vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      - name: Install - Bundler
        env:
          MAKE: make -j2
        working-directory: .
        run: |
          bundle config set path vendor/bundle
          bundle install --jobs=4 --retry=3
          bundle clean

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Copy _redirects to _site and list files
        run: |
          cp _redirects _site/
          find _site

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          projectName: aibtra-website
          directory: ./_site
